import type { ActivityDefinition } from '../../types';

export const browserActivities: ActivityDefinition[] = [
  {
    id: 'use-app-browser',
    name: 'Use Application/Browser',
    category: 'browser',
    group: 'Application',
    icon: '🖥',
    description: 'Attaches to or opens a browser/application and runs child activities inside it',
    color: '#C75000',
    nodeType: 'activity',
    isContainer: true,
    properties: [
      { name: 'displayName', label: 'Display name', type: 'string', defaultValue: 'Use Application/Browser' },
      { name: 'url', label: 'URL', type: 'expression', defaultValue: '', description: 'URL to open in the browser (leave blank for desktop apps)' },
      { name: 'windowTitle', label: 'Window Title', type: 'string', defaultValue: '', description: 'Title of the target application window' },
      { name: 'browser', label: 'Browser', type: 'select', defaultValue: 'Chrome', options: [
        { label: 'Chrome', value: 'Chrome' },
        { label: 'Edge', value: 'Edge' },
        { label: 'Firefox', value: 'Firefox' },
      ]},
      { name: 'inputMode', label: 'Input mode', type: 'select', defaultValue: 'HardwareEvents', options: [
        { label: 'Hardware Events', value: 'HardwareEvents' },
        { label: 'Simulate', value: 'Simulate' },
        { label: 'ChromiumAPI', value: 'ChromiumAPI' },
      ]},
      { name: 'open', label: 'Open', type: 'select', defaultValue: 'Always', options: [
        { label: 'Always', value: 'Always' },
        { label: 'IfNotOpen', value: 'IfNotOpen' },
        { label: 'Never', value: 'Never' },
      ]},
      { name: 'close', label: 'Close', type: 'select', defaultValue: 'Never', options: [
        { label: 'Never', value: 'Never' },
        { label: 'Always', value: 'Always' },
        { label: 'IfOpenedByAppBrowser', value: 'IfOpenedByAppBrowser' },
      ]},
      { name: 'incognito', label: 'Incognito/private window', type: 'boolean', defaultValue: false },
      { name: 'private', label: 'Private', type: 'boolean', defaultValue: false },
    ],
  },
  {
    id: 'open-browser',
    name: 'Open Browser',
    category: 'browser',
    group: 'Application',
    icon: '🌐',
    description: 'Launches a browser and navigates to a URL',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [
      { name: 'url', label: 'URL', type: 'expression', defaultValue: 'https://', required: true },
      { name: 'browser', label: 'Browser', type: 'select', defaultValue: 'Chrome', options: [
        { label: 'Chrome', value: 'Chrome' },
        { label: 'Edge', value: 'Edge' },
        { label: 'Firefox', value: 'Firefox' },
      ]},
      { name: 'headless', label: 'Headless Mode', type: 'boolean', defaultValue: false },
      { name: 'timeout', label: 'Page Load Timeout (ms)', type: 'number', defaultValue: 30000 },
    ],
  },
  {
    id: 'close-browser',
    name: 'Close Browser',
    category: 'browser',
    group: 'Application',
    icon: '✕',
    description: 'Closes the browser window',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [
      { name: 'closeAll', label: 'Close All Windows', type: 'boolean', defaultValue: false },
    ],
  },
  {
    id: 'navigate-to',
    name: 'Navigate To',
    category: 'browser',
    group: 'Navigation',
    icon: '→',
    description: 'Navigates to a URL in the current tab',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [
      { name: 'url', label: 'URL', type: 'expression', defaultValue: '', required: true },
      { name: 'waitUntil', label: 'Wait Until', type: 'select', defaultValue: 'load', options: [
        { label: 'Page Load', value: 'load' },
        { label: 'DOM Ready', value: 'domcontentloaded' },
        { label: 'Network Idle', value: 'networkidle' },
      ]},
    ],
  },
  {
    id: 'navigate-back',
    name: 'Navigate Back',
    category: 'browser',
    group: 'Navigation',
    icon: '←',
    description: 'Navigates to the previous page in browser history',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [],
  },
  {
    id: 'navigate-forward',
    name: 'Navigate Forward',
    category: 'browser',
    group: 'Navigation',
    icon: '→',
    description: 'Navigates to the next page in browser history',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [],
  },
  {
    id: 'refresh-page',
    name: 'Refresh Page',
    category: 'browser',
    group: 'Navigation',
    icon: '↻',
    description: 'Reloads the current browser page',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [
      { name: 'hardRefresh', label: 'Hard Refresh (bypass cache)', type: 'boolean', defaultValue: false },
    ],
  },
  {
    id: 'open-new-tab',
    name: 'Open New Tab',
    category: 'browser',
    group: 'Tabs & Frames',
    icon: '📑',
    description: 'Opens a new browser tab and optionally navigates to a URL',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [
      { name: 'url', label: 'URL (optional)', type: 'expression', defaultValue: '' },
    ],
  },
  {
    id: 'close-tab',
    name: 'Close Tab',
    category: 'browser',
    group: 'Tabs & Frames',
    icon: '✕',
    description: 'Closes the current browser tab',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [],
  },
  {
    id: 'switch-tab',
    name: 'Switch To Tab',
    category: 'browser',
    group: 'Tabs & Frames',
    icon: '⇥',
    description: 'Switches focus to a browser tab by title or index',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [
      { name: 'switchBy', label: 'Switch By', type: 'select', defaultValue: 'Title', options: [
        { label: 'Title (contains)', value: 'Title' },
        { label: 'Index (0-based)', value: 'Index' },
        { label: 'URL (contains)', value: 'URL' },
      ]},
      { name: 'value', label: 'Value', type: 'expression', defaultValue: '', required: true },
    ],
  },
  {
    id: 'switch-frame',
    name: 'Switch To Frame',
    category: 'browser',
    group: 'Tabs & Frames',
    icon: '⊡',
    description: 'Switches context into an iframe element',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Frame Selector', type: 'string', defaultValue: '', required: true, description: 'CSS selector or name attribute of the iframe' },
    ],
  },
  {
    id: 'switch-default-content',
    name: 'Switch To Default',
    category: 'browser',
    group: 'Tabs & Frames',
    icon: '⊞',
    description: 'Switches back to the main page from an iframe context',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [],
  },
  {
    id: 'accept-alert',
    name: 'Accept Alert',
    category: 'browser',
    group: 'Dialogs',
    icon: '✓',
    description: 'Accepts (OK) a browser alert, confirm, or prompt dialog',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [
      { name: 'promptText', label: 'Prompt Input (optional)', type: 'expression', defaultValue: '', description: 'Text to enter if dialog is a prompt' },
    ],
  },
  {
    id: 'dismiss-alert',
    name: 'Dismiss Alert',
    category: 'browser',
    group: 'Dialogs',
    icon: '✕',
    description: 'Dismisses (Cancel) a browser dialog',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [],
  },
  {
    id: 'maximize-window',
    name: 'Maximize Window',
    category: 'browser',
    group: 'Application',
    icon: '⊡',
    description: 'Maximizes or sets the browser window size',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [
      { name: 'mode', label: 'Mode', type: 'select', defaultValue: 'Maximize', options: [
        { label: 'Maximize', value: 'Maximize' },
        { label: 'Minimize', value: 'Minimize' },
        { label: 'Custom Size', value: 'Custom' },
      ]},
      { name: 'width', label: 'Width (px)', type: 'number', defaultValue: 1280 },
      { name: 'height', label: 'Height (px)', type: 'number', defaultValue: 800 },
    ],
  },
  {
    id: 'execute-javascript',
    name: 'Execute JavaScript',
    category: 'browser',
    group: 'Code',
    icon: '⚡',
    description: 'Runs JavaScript code in the browser context',
    color: '#0277BD',
    nodeType: 'activity',
    properties: [
      { name: 'script', label: 'Script', type: 'expression', defaultValue: 'return document.title;', required: true },
      { name: 'output', label: 'Output Variable', type: 'variable', defaultValue: 'jsResult' },
    ],
  },
];
