import type { ActivityDefinition } from '../../types';

export const controlFlowActivities: ActivityDefinition[] = [
  {
    id: 'sequence',
    name: 'Sequence',
    category: 'controlFlow',
    icon: '▶',
    description: 'Executes activities in sequential order',
    color: '#2E7D32',
    nodeType: 'sequence',
    properties: [
      {
        name: 'displayName',
        label: 'Display Name',
        type: 'string',
        defaultValue: 'Sequence',
      },
    ],
  },
  {
    id: 'if',
    name: 'If',
    category: 'controlFlow',
    icon: '◇',
    description: 'Conditional branching based on a condition',
    color: '#E65100',
    nodeType: 'decision',
    isContainer: true,
    properties: [
      {
        name: 'displayName',
        label: 'Display Name',
        type: 'string',
        defaultValue: 'If',
      },
    ],
  },
  {
    id: 'while',
    name: 'While',
    category: 'controlFlow',
    icon: '🔄',
    description: 'Repeats while condition is true',
    color: '#6A1B9A',
    nodeType: 'loop',
    properties: [
      {
        name: 'condition',
        label: 'Condition',
        type: 'expression',
        defaultValue: '',
        required: true,
      },
    ],
  },
  {
    id: 'for-each',
    name: 'For Each',
    category: 'controlFlow',
    icon: '🔁',
    description: 'Iterates over each item in a collection',
    color: '#6A1B9A',
    nodeType: 'loop',
    isContainer: true,
    properties: [
      {
        name: 'collection',
        label: 'Collection',
        type: 'expression',
        defaultValue: '',
        required: true,
      },
    ],
  },
  {
    id: 'try-catch',
    name: 'Try Catch',
    category: 'controlFlow',
    icon: '🛡',
    description: 'Catches and handles runtime exceptions',
    color: '#B71C1C',
    nodeType: 'sequence',
    isContainer: true,
    properties: [
      {
        name: 'exception',
        label: 'Exception Variable',
        type: 'variable',
        defaultValue: 'exception',
      },
    ],
  },
  {
    id: 'retry-scope',
    name: 'Retry Scope',
    category: 'controlFlow',
    icon: '↻',
    description: 'Retries contained activities after a failure',
    color: '#6A1B9A',
    nodeType: 'loop',
    isContainer: true,
    properties: [
      { name: 'maxRetries', label: 'Maximum Retries', type: 'number', defaultValue: 3, required: true },
      { name: 'retryDelay', label: 'Retry Delay (ms)', type: 'number', defaultValue: 1000, required: true },
    ],
  },
  {
    id: 'break',
    name: 'Break',
    category: 'controlFlow',
    icon: '⏹',
    description: 'Breaks out of the current loop',
    color: '#6A1B9A',
    nodeType: 'activity',
    properties: [],
  },
  {
    id: 'continue',
    name: 'Continue',
    category: 'controlFlow',
    icon: '⏭',
    description: 'Skips to the next iteration of the current loop',
    color: '#6A1B9A',
    nodeType: 'activity',
    properties: [],
  },
];
