import type { ActivityDefinition } from '../../types';

export const dataActivities: ActivityDefinition[] = [
  {
    id: 'create-list',
    name: 'Create List',
    category: 'data',
    icon: '☷',
    description: 'Creates an empty list and stores it in a variable',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      { name: 'output', label: 'Output Variable', type: 'variable', defaultValue: 'items', required: true },
    ],
  },
  {
    id: 'add-to-collection',
    name: 'Add To Collection',
    category: 'data',
    icon: '⊕',
    description: 'Adds a value to a list variable',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      { name: 'collection', label: 'Collection Variable', type: 'variable', defaultValue: '', required: true },
      { name: 'value', label: 'Value', type: 'expression', defaultValue: '', required: true },
    ],
  },
  {
    id: 'remove-from-collection',
    name: 'Remove From Collection',
    category: 'data',
    icon: '⊖',
    description: 'Removes the first matching value from a list variable',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      { name: 'collection', label: 'Collection Variable', type: 'variable', defaultValue: '', required: true },
      { name: 'value', label: 'Value', type: 'expression', defaultValue: '', required: true },
    ],
  },
  {
    id: 'clear-collection',
    name: 'Clear Collection',
    category: 'data',
    icon: '⌫',
    description: 'Removes all items from a list variable',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      { name: 'collection', label: 'Collection Variable', type: 'variable', defaultValue: '', required: true },
    ],
  },
  {
    id: 'create-folder',
    name: 'Create Folder',
    category: 'data',
    icon: '📁',
    description: 'Creates a folder when it does not already exist',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      { name: 'path', label: 'Folder Path', type: 'expression', defaultValue: '', required: true },
    ],
  },
  {
    id: 'get-files',
    name: 'Get Files',
    category: 'data',
    icon: '🗂',
    description: 'Lists files in a folder and saves their paths to a variable',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      { name: 'folder', label: 'Folder Path', type: 'expression', defaultValue: '', required: true },
      { name: 'filter', label: 'Search Pattern', type: 'string', defaultValue: '*.*' },
      { name: 'output', label: 'Output Variable', type: 'variable', defaultValue: 'files', required: true },
    ],
  },
  {
    id: 'copy-file',
    name: 'Copy File',
    category: 'data',
    icon: '📄',
    description: 'Copies a file to a new path',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      { name: 'source', label: 'Source Path', type: 'expression', defaultValue: '', required: true },
      { name: 'destination', label: 'Destination Path', type: 'expression', defaultValue: '', required: true },
      { name: 'overwrite', label: 'Overwrite Existing', type: 'boolean', defaultValue: false },
    ],
  },
  {
    id: 'move-file',
    name: 'Move File',
    category: 'data',
    icon: '➡',
    description: 'Moves a file to a new path',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      { name: 'source', label: 'Source Path', type: 'expression', defaultValue: '', required: true },
      { name: 'destination', label: 'Destination Path', type: 'expression', defaultValue: '', required: true },
      { name: 'overwrite', label: 'Overwrite Existing', type: 'boolean', defaultValue: false },
    ],
  },
  {
    id: 'delete-file',
    name: 'Delete File',
    category: 'data',
    icon: '🗑',
    description: 'Deletes a file from disk',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      { name: 'path', label: 'File Path', type: 'expression', defaultValue: '', required: true },
    ],
  },
  {
    id: 'read-file',
    name: 'Read File',
    category: 'data',
    icon: '📂',
    description: 'Reads content from a file',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      {
        name: 'path',
        label: 'File Path',
        type: 'expression',
        defaultValue: '',
        required: true,
      },
      {
        name: 'output',
        label: 'Output Variable',
        type: 'variable',
        defaultValue: 'fileContent',
        required: true,
      },
      {
        name: 'encoding',
        label: 'Encoding',
        type: 'select',
        defaultValue: 'UTF-8',
        options: [
          { label: 'UTF-8', value: 'UTF-8' },
          { label: 'ASCII', value: 'ASCII' },
          { label: 'Unicode', value: 'Unicode' },
        ],
      },
    ],
  },
  {
    id: 'write-file',
    name: 'Write File',
    category: 'data',
    icon: '💾',
    description: 'Writes content to a file',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      {
        name: 'path',
        label: 'File Path',
        type: 'expression',
        defaultValue: '',
        required: true,
      },
      {
        name: 'content',
        label: 'Content',
        type: 'expression',
        defaultValue: '',
        required: true,
      },
      {
        name: 'append',
        label: 'Append Mode',
        type: 'boolean',
        defaultValue: false,
      },
    ],
  },
  {
    id: 'read-csv',
    name: 'Read CSV',
    category: 'data',
    icon: 'CSV',
    description: 'Reads a CSV file into a table of named rows',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      { name: 'path', label: 'CSV File Path', type: 'expression', defaultValue: '', required: true },
      { name: 'hasHeaders', label: 'First Row Has Headers', type: 'boolean', defaultValue: true },
      { name: 'output', label: 'Output Variable', type: 'variable', defaultValue: 'csvData', required: true },
    ],
  },
  {
    id: 'write-csv',
    name: 'Write CSV',
    category: 'data',
    icon: 'CSV',
    description: 'Writes a table variable to a CSV file',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      { name: 'path', label: 'CSV File Path', type: 'expression', defaultValue: '', required: true },
      { name: 'data', label: 'Table Variable', type: 'variable', defaultValue: '', required: true },
      { name: 'includeHeaders', label: 'Write Headers', type: 'boolean', defaultValue: true },
    ],
  },
  {
    id: 'http-request',
    name: 'HTTP Request',
    category: 'data',
    icon: '🔌',
    description: 'Sends an HTTP request to an endpoint',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      {
        name: 'url',
        label: 'URL',
        type: 'expression',
        defaultValue: '',
        required: true,
      },
      {
        name: 'method',
        label: 'Method',
        type: 'select',
        defaultValue: 'GET',
        options: [
          { label: 'GET', value: 'GET' },
          { label: 'POST', value: 'POST' },
          { label: 'PUT', value: 'PUT' },
          { label: 'DELETE', value: 'DELETE' },
          { label: 'PATCH', value: 'PATCH' },
        ],
      },
      {
        name: 'body',
        label: 'Body',
        type: 'expression',
        defaultValue: '',
      },
      {
        name: 'output',
        label: 'Output Variable',
        type: 'variable',
        defaultValue: 'response',
        required: true,
      },
    ],
  },
  {
    id: 'json-deserialize',
    name: 'Deserialize JSON',
    category: 'data',
    icon: '📊',
    description: 'Parses a JSON string into an object',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      {
        name: 'jsonString',
        label: 'JSON String',
        type: 'expression',
        defaultValue: '',
        required: true,
      },
      {
        name: 'output',
        label: 'Output Variable',
        type: 'variable',
        defaultValue: 'jsonObject',
        required: true,
      },
    ],
  },
];
