import type { ActivityDefinition } from '../../types';

export const dataExtractionActivities: ActivityDefinition[] = [
  {
    id: 'get-text',
    name: 'Get Text',
    category: 'dataExtraction',
    group: 'Element',
    icon: '📖',
    description: 'Reads the visible text content of an element and saves it to a variable',
    color: '#00838F',
    nodeType: 'activity',
    properties: [
      { name: 'displayName', label: 'Display name', type: 'string', defaultValue: 'Get Text' },
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true, description: 'CSS selector or XPath of the target element' },
      { name: 'output', label: 'Output Variable', type: 'variable', defaultValue: 'textResult', required: true, description: 'Variable to store the extracted text' },
      { name: 'trim', label: 'Trim Whitespace', type: 'boolean', defaultValue: true },
      { name: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 30000 },
    ],
  },
  {
    id: 'get-attribute',
    name: 'Get Attribute',
    category: 'dataExtraction',
    group: 'Element',
    icon: '🏷',
    description: 'Reads the value of an HTML attribute from an element',
    color: '#00838F',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true },
      { name: 'attribute', label: 'Attribute Name', type: 'string', defaultValue: 'href', required: true, description: 'e.g. href, src, class, id, value' },
      { name: 'output', label: 'Output Variable', type: 'variable', defaultValue: 'attrValue', required: true },
    ],
  },
  {
    id: 'get-value',
    name: 'Get Value',
    category: 'dataExtraction',
    group: 'Element',
    icon: '✏',
    description: 'Reads the current value of an input, select, or textarea',
    color: '#00838F',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true },
      { name: 'output', label: 'Output Variable', type: 'variable', defaultValue: 'inputValue', required: true },
    ],
  },
  {
    id: 'get-inner-html',
    name: 'Get Inner HTML',
    category: 'dataExtraction',
    group: 'Element',
    icon: '📋',
    description: 'Returns the raw HTML inside an element',
    color: '#00838F',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true },
      { name: 'output', label: 'Output Variable', type: 'variable', defaultValue: 'html', required: true },
    ],
  },
  {
    id: 'get-element-count',
    name: 'Get Element Count',
    category: 'dataExtraction',
    group: 'Element',
    icon: '🔢',
    description: 'Counts how many elements match a given selector',
    color: '#00838F',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true },
      { name: 'output', label: 'Output Variable', type: 'variable', defaultValue: 'count', required: true },
    ],
  },
  {
    id: 'extract-table',
    name: 'Extract Table',
    category: 'dataExtraction',
    group: 'Table',
    icon: '🗂',
    description: 'Extracts an HTML table into a structured data table',
    color: '#00838F',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Table Selector', type: 'string', defaultValue: 'table', required: true },
      { name: 'output', label: 'Output Variable', type: 'variable', defaultValue: 'tableData', required: true },
      { name: 'includeHeader', label: 'Include Header Row', type: 'boolean', defaultValue: true },
    ],
  },
  {
    id: 'find-elements',
    name: 'Find Elements',
    category: 'dataExtraction',
    group: 'Element',
    icon: '🔍',
    description: 'Returns a list of all elements matching a selector',
    color: '#00838F',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true },
      { name: 'output', label: 'Output Variable', type: 'variable', defaultValue: 'elements', required: true },
    ],
  },
  {
    id: 'get-page-title',
    name: 'Get Page Title',
    category: 'dataExtraction',
    group: 'Page',
    icon: '📌',
    description: 'Returns the title of the current browser page',
    color: '#00838F',
    nodeType: 'activity',
    properties: [
      { name: 'output', label: 'Output Variable', type: 'variable', defaultValue: 'pageTitle', required: true },
    ],
  },
  {
    id: 'get-page-url',
    name: 'Get Page URL',
    category: 'dataExtraction',
    group: 'Page',
    icon: '🔗',
    description: 'Returns the current URL of the browser page',
    color: '#00838F',
    nodeType: 'activity',
    properties: [
      { name: 'output', label: 'Output Variable', type: 'variable', defaultValue: 'currentUrl', required: true },
    ],
  },
  {
    id: 'get-all-text',
    name: 'Get All Text',
    category: 'dataExtraction',
    group: 'Element',
    icon: '📄',
    description: 'Returns the text content of all matched elements as a list',
    color: '#00838F',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true },
      { name: 'output', label: 'Output Variable', type: 'variable', defaultValue: 'textList', required: true },
      { name: 'separator', label: 'Join Separator', type: 'string', defaultValue: '', description: 'Leave empty to return as array' },
    ],
  },
];
