import type { ActivityDefinition } from '../../types';

export const dataActivities: ActivityDefinition[] = [
  {
    id: 'read-file',
    name: 'Read File',
    category: 'data',
    icon: '📂',
    description: 'Reads content from a file',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      {
        name: 'path',
        label: 'File Path',
        type: 'expression',
        defaultValue: '',
        required: true,
      },
      {
        name: 'output',
        label: 'Output Variable',
        type: 'variable',
        defaultValue: 'fileContent',
        required: true,
      },
      {
        name: 'encoding',
        label: 'Encoding',
        type: 'select',
        defaultValue: 'UTF-8',
        options: [
          { label: 'UTF-8', value: 'UTF-8' },
          { label: 'ASCII', value: 'ASCII' },
          { label: 'Unicode', value: 'Unicode' },
        ],
      },
    ],
  },
  {
    id: 'write-file',
    name: 'Write File',
    category: 'data',
    icon: '💾',
    description: 'Writes content to a file',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      {
        name: 'path',
        label: 'File Path',
        type: 'expression',
        defaultValue: '',
        required: true,
      },
      {
        name: 'content',
        label: 'Content',
        type: 'expression',
        defaultValue: '',
        required: true,
      },
      {
        name: 'append',
        label: 'Append Mode',
        type: 'boolean',
        defaultValue: false,
      },
    ],
  },
  {
    id: 'http-request',
    name: 'HTTP Request',
    category: 'data',
    icon: '🔌',
    description: 'Sends an HTTP request to an endpoint',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      {
        name: 'url',
        label: 'URL',
        type: 'expression',
        defaultValue: '',
        required: true,
      },
      {
        name: 'method',
        label: 'Method',
        type: 'select',
        defaultValue: 'GET',
        options: [
          { label: 'GET', value: 'GET' },
          { label: 'POST', value: 'POST' },
          { label: 'PUT', value: 'PUT' },
          { label: 'DELETE', value: 'DELETE' },
          { label: 'PATCH', value: 'PATCH' },
        ],
      },
      {
        name: 'body',
        label: 'Body',
        type: 'expression',
        defaultValue: '',
      },
      {
        name: 'output',
        label: 'Output Variable',
        type: 'variable',
        defaultValue: 'response',
        required: true,
      },
    ],
  },
  {
    id: 'json-deserialize',
    name: 'Deserialize JSON',
    category: 'data',
    icon: '📊',
    description: 'Parses a JSON string into an object',
    color: '#00695C',
    nodeType: 'activity',
    properties: [
      {
        name: 'jsonString',
        label: 'JSON String',
        type: 'expression',
        defaultValue: '',
        required: true,
      },
      {
        name: 'output',
        label: 'Output Variable',
        type: 'variable',
        defaultValue: 'jsonObject',
        required: true,
      },
    ],
  },
];
