import type { ActivityDefinition } from '../../types';

export const systemActivities: ActivityDefinition[] = [
  {
    id: 'end',
    name: 'End',
    category: 'system',
    icon: '⏹',
    description: 'Marks the end of the workflow',
    color: '#E53935',
    nodeType: 'end',
    properties: [],
  },
  {
    id: 'write-line',
    name: 'Write Line',
    category: 'system',
    icon: '📝',
    description: 'Writes a line of text to output',
    color: '#4A90D9',
    nodeType: 'activity',
    properties: [
      {
        name: 'text',
        label: 'Text',
        type: 'expression',
        defaultValue: '',
        required: true,
        description: 'The text to write',
      },
    ],
  },
  {
    id: 'assign',
    name: 'Assign',
    category: 'system',
    icon: '📌',
    description: 'Assigns a value to a variable',
    color: '#4A90D9',
    nodeType: 'activity',
    properties: [
      {
        name: 'to',
        label: 'To (Variable)',
        type: 'variable',
        defaultValue: '',
        required: true,
        description: 'Variable to assign to',
      },
      {
        name: 'value',
        label: 'Value',
        type: 'expression',
        defaultValue: '',
        required: true,
        description: 'Value to assign',
      },
    ],
  },
  {
    id: 'delay',
    name: 'Delay',
    category: 'system',
    icon: '⏱',
    description: 'Pauses execution for a duration',
    color: '#4A90D9',
    nodeType: 'activity',
    properties: [
      {
        name: 'duration',
        label: 'Duration (ms)',
        type: 'number',
        defaultValue: 1000,
        required: true,
        description: 'Duration in milliseconds',
      },
    ],
  },
  {
    id: 'log-message',
    name: 'Log Message',
    category: 'system',
    icon: '📋',
    description: 'Logs a message to the output panel',
    color: '#4A90D9',
    nodeType: 'activity',
    properties: [
      {
        name: 'message',
        label: 'Message',
        type: 'expression',
        defaultValue: '',
        required: true,
      },
      {
        name: 'level',
        label: 'Level',
        type: 'select',
        defaultValue: 'Info',
        options: [
          { label: 'Info', value: 'Info' },
          { label: 'Warning', value: 'Warning' },
          { label: 'Error', value: 'Error' },
          { label: 'Debug', value: 'Debug' },
        ],
      },
    ],
  },
  {
    id: 'invoke-workflow',
    name: 'Invoke Workflow',
    category: 'system',
    icon: '🔗',
    description: 'Invokes another workflow file',
    color: '#4A90D9',
    nodeType: 'activity',
    properties: [
      {
        name: 'workflowFile',
        label: 'Workflow File',
        type: 'string',
        defaultValue: '',
        required: true,
        description: 'Path to the workflow .xaml file',
      },
    ],
  },
  {
    id: 'throw',
    name: 'Throw',
    category: 'system',
    icon: '⚠',
    description: 'Stops the current activity path with an error message',
    color: '#C50F1F',
    nodeType: 'activity',
    properties: [
      { name: 'message', label: 'Exception Message', type: 'expression', defaultValue: 'Workflow error', required: true },
    ],
  },
  {
    id: 'run-script-file',
    name: 'Run Script File',
    category: 'system',
    group: 'Code',
    icon: '▶',
    description: 'Runs an existing PowerShell, Python, or C# (.NET) script file',
    color: '#4A90D9',
    nodeType: 'activity',
    properties: [
      { name: 'path', label: 'Script File Path', type: 'expression', defaultValue: '', required: true, description: 'Supported: .ps1, .py, .csx, and .cs' },
      { name: 'language', label: 'Language', type: 'select', defaultValue: 'Auto Detect', options: [
        { label: 'Auto Detect from Extension', value: 'Auto Detect' },
        { label: 'PowerShell', value: 'PowerShell' },
        { label: 'Python', value: 'Python' },
        { label: 'C# (.NET)', value: 'C#' },
      ] },
      { name: 'arguments', label: 'Arguments', type: 'expression', defaultValue: '', description: 'Optional command-line arguments; quote values containing spaces' },
      { name: 'output', label: 'Standard Output Variable', type: 'variable', defaultValue: 'scriptOutput', description: 'Optional variable that receives standard output' },
    ],
  },
  {
    id: 'run-script-code',
    name: 'Run Script Code',
    category: 'system',
    group: 'Code',
    icon: '⌨',
    description: 'Opens the script editor and runs PowerShell, Python, or C# (.NET) code',
    color: '#4A90D9',
    nodeType: 'activity',
    properties: [
      { name: 'language', label: 'Language', type: 'select', defaultValue: 'PowerShell', options: [
        { label: 'PowerShell', value: 'PowerShell' },
        { label: 'Python', value: 'Python' },
        { label: 'C# (.NET)', value: 'C#' },
      ] },
      { name: 'code', label: 'Script', type: 'code', defaultValue: '', required: true, description: 'Write code here. Type {{ to insert a workflow variable or its members.' },
      { name: 'arguments', label: 'Arguments', type: 'expression', defaultValue: '', description: 'Optional command-line arguments; quote values containing spaces' },
      { name: 'output', label: 'Standard Output Variable', type: 'variable', defaultValue: 'scriptOutput', description: 'Optional variable that receives standard output' },
    ],
  },
];
