import type { ActivityDefinition } from '../../types';

export const systemActivities: ActivityDefinition[] = [
  {
    id: 'end',
    name: 'End',
    category: 'system',
    icon: '⏹',
    description: 'Marks the end of the workflow',
    color: '#E53935',
    nodeType: 'end',
    properties: [],
  },
  {
    id: 'write-line',
    name: 'Write Line',
    category: 'system',
    icon: '📝',
    description: 'Writes a line of text to output',
    color: '#4A90D9',
    nodeType: 'activity',
    properties: [
      {
        name: 'text',
        label: 'Text',
        type: 'expression',
        defaultValue: '',
        required: true,
        description: 'The text to write',
      },
    ],
  },
  {
    id: 'assign',
    name: 'Assign',
    category: 'system',
    icon: '📌',
    description: 'Assigns a value to a variable',
    color: '#4A90D9',
    nodeType: 'activity',
    properties: [
      {
        name: 'to',
        label: 'To (Variable)',
        type: 'variable',
        defaultValue: '',
        required: true,
        description: 'Variable to assign to',
      },
      {
        name: 'value',
        label: 'Value',
        type: 'expression',
        defaultValue: '',
        required: true,
        description: 'Value to assign',
      },
    ],
  },
  {
    id: 'delay',
    name: 'Delay',
    category: 'system',
    icon: '⏱',
    description: 'Pauses execution for a duration',
    color: '#4A90D9',
    nodeType: 'activity',
    properties: [
      {
        name: 'duration',
        label: 'Duration (ms)',
        type: 'number',
        defaultValue: 1000,
        required: true,
        description: 'Duration in milliseconds',
      },
    ],
  },
  {
    id: 'log-message',
    name: 'Log Message',
    category: 'system',
    icon: '📋',
    description: 'Logs a message to the output panel',
    color: '#4A90D9',
    nodeType: 'activity',
    properties: [
      {
        name: 'message',
        label: 'Message',
        type: 'expression',
        defaultValue: '',
        required: true,
      },
      {
        name: 'level',
        label: 'Level',
        type: 'select',
        defaultValue: 'Info',
        options: [
          { label: 'Info', value: 'Info' },
          { label: 'Warning', value: 'Warning' },
          { label: 'Error', value: 'Error' },
          { label: 'Debug', value: 'Debug' },
        ],
      },
    ],
  },
  {
    id: 'invoke-workflow',
    name: 'Invoke Workflow',
    category: 'system',
    icon: '🔗',
    description: 'Invokes another workflow file',
    color: '#4A90D9',
    nodeType: 'activity',
    properties: [
      {
        name: 'workflowFile',
        label: 'Workflow File',
        type: 'string',
        defaultValue: '',
        required: true,
        description: 'Path to the workflow .xaml file',
      },
    ],
  },
];
