import type { ActivityDefinition } from '../../types';

export const uiAutomationActivities: ActivityDefinition[] = [
  {
    id: 'click',
    name: 'Click',
    category: 'uiAutomation',
    group: 'Element',
    icon: '🖱',
    description: 'Clicks a UI element',
    color: '#1565C0',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true, description: 'CSS selector or XPath' },
      { name: 'clickType', label: 'Click Type', type: 'select', defaultValue: 'Left', options: [
        { label: 'Left Click', value: 'Left' },
        { label: 'Right Click', value: 'Right' },
        { label: 'Double Click', value: 'Double' },
        { label: 'Middle Click', value: 'Middle' },
      ]},
      { name: 'waitBefore', label: 'Wait Before (ms)', type: 'number', defaultValue: 0 },
      { name: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 30000 },
    ],
  },
  {
    id: 'double-click',
    name: 'Double Click',
    category: 'uiAutomation',
    group: 'Element',
    icon: '🖱',
    description: 'Double-clicks a UI element',
    color: '#1565C0',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true },
      { name: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 30000 },
    ],
  },
  {
    id: 'right-click',
    name: 'Right Click',
    category: 'uiAutomation',
    group: 'Element',
    icon: '🖱',
    description: 'Right-clicks an element to open the context menu',
    color: '#1565C0',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true },
      { name: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 30000 },
    ],
  },
  {
    id: 'hover',
    name: 'Hover',
    category: 'uiAutomation',
    group: 'Element',
    icon: '✋',
    description: 'Moves the mouse over an element without clicking',
    color: '#1565C0',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true },
      { name: 'duration', label: 'Hold Duration (ms)', type: 'number', defaultValue: 500 },
    ],
  },
  {
    id: 'type-into',
    name: 'Type Into',
    category: 'uiAutomation',
    group: 'Text',
    icon: '⌨',
    description: 'Types text into an input or textarea element',
    color: '#1565C0',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true },
      { name: 'text', label: 'Text', type: 'expression', defaultValue: '', required: true },
      { name: 'clearBefore', label: 'Clear Before Typing', type: 'boolean', defaultValue: true },
      { name: 'delay', label: 'Key Delay (ms)', type: 'number', defaultValue: 50, description: 'Delay between keystrokes' },
    ],
  },
  {
    id: 'clear-text',
    name: 'Clear Text',
    category: 'uiAutomation',
    group: 'Text',
    icon: '🗑',
    description: 'Clears all text from an input field',
    color: '#1565C0',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true },
    ],
  },
  {
    id: 'send-hotkey',
    name: 'Send Hotkey',
    category: 'uiAutomation',
    group: 'Keyboard',
    icon: '⌨',
    description: 'Sends a keyboard shortcut or special key combination',
    color: '#1565C0',
    nodeType: 'activity',
    properties: [
      { name: 'key', label: 'Key Combination', type: 'select', defaultValue: 'Enter', options: [
        { label: 'Enter', value: 'Enter' },
        { label: 'Tab', value: 'Tab' },
        { label: 'Escape', value: 'Escape' },
        { label: 'Ctrl+C (Copy)', value: 'Ctrl+C' },
        { label: 'Ctrl+V (Paste)', value: 'Ctrl+V' },
        { label: 'Ctrl+A (Select All)', value: 'Ctrl+A' },
        { label: 'Ctrl+Z (Undo)', value: 'Ctrl+Z' },
        { label: 'Ctrl+S (Save)', value: 'Ctrl+S' },
        { label: 'Ctrl+F (Find)', value: 'Ctrl+F' },
        { label: 'F5 (Refresh)', value: 'F5' },
        { label: 'Delete', value: 'Delete' },
        { label: 'Backspace', value: 'Backspace' },
        { label: 'Alt+F4 (Close)', value: 'Alt+F4' },
        { label: 'Page Down', value: 'PageDown' },
        { label: 'Page Up', value: 'PageUp' },
        { label: 'End', value: 'End' },
        { label: 'Home', value: 'Home' },
      ]},
      { name: 'selector', label: 'Target Element (optional)', type: 'string', defaultValue: '', description: 'Leave empty to send globally' },
    ],
  },
  {
    id: 'select-option',
    name: 'Select Option',
    category: 'uiAutomation',
    group: 'Forms',
    icon: '▽',
    description: 'Selects an item from a dropdown or select element',
    color: '#1565C0',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true },
      { name: 'value', label: 'Value / Text / Index', type: 'expression', defaultValue: '', required: true },
      { name: 'selectBy', label: 'Select By', type: 'select', defaultValue: 'Text', options: [
        { label: 'Visible Text', value: 'Text' },
        { label: 'Value Attribute', value: 'Value' },
        { label: 'Index (0-based)', value: 'Index' },
      ]},
    ],
  },
  {
    id: 'check-checkbox',
    name: 'Check/Uncheck',
    category: 'uiAutomation',
    group: 'Forms',
    icon: '☑',
    description: 'Sets the checked state of a checkbox or radio button',
    color: '#1565C0',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true },
      { name: 'checked', label: 'Checked State', type: 'boolean', defaultValue: true },
    ],
  },
  {
    id: 'drag-drop',
    name: 'Drag And Drop',
    category: 'uiAutomation',
    group: 'Element',
    icon: '⇄',
    description: 'Drags an element and drops it onto a target',
    color: '#1565C0',
    nodeType: 'activity',
    properties: [
      { name: 'source', label: 'Source Selector', type: 'string', defaultValue: '', required: true },
      { name: 'target', label: 'Target Selector', type: 'string', defaultValue: '', required: true },
      { name: 'speed', label: 'Drag Speed (ms)', type: 'number', defaultValue: 500 },
    ],
  },
  {
    id: 'scroll-to',
    name: 'Scroll To Element',
    category: 'uiAutomation',
    group: 'Element',
    icon: '↕',
    description: 'Scrolls the page until an element is visible',
    color: '#1565C0',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'Selector', type: 'string', defaultValue: '', required: true },
      { name: 'block', label: 'Alignment', type: 'select', defaultValue: 'center', options: [
        { label: 'Center', value: 'center' },
        { label: 'Start (top)', value: 'start' },
        { label: 'End (bottom)', value: 'end' },
      ]},
    ],
  },
  {
    id: 'scroll-page',
    name: 'Scroll Page',
    category: 'uiAutomation',
    group: 'Page',
    icon: '↕',
    description: 'Scrolls the page in a given direction',
    color: '#1565C0',
    nodeType: 'activity',
    properties: [
      { name: 'direction', label: 'Direction', type: 'select', defaultValue: 'Down', options: [
        { label: 'Down', value: 'Down' },
        { label: 'Up', value: 'Up' },
        { label: 'To Bottom', value: 'Bottom' },
        { label: 'To Top', value: 'Top' },
      ]},
      { name: 'amount', label: 'Amount (px)', type: 'number', defaultValue: 500 },
    ],
  },
  {
    id: 'upload-file',
    name: 'Upload File',
    category: 'uiAutomation',
    group: 'File',
    icon: '📤',
    description: 'Sets a file path on a file input element',
    color: '#1565C0',
    nodeType: 'activity',
    properties: [
      { name: 'selector', label: 'File Input Selector', type: 'string', defaultValue: '', required: true },
      { name: 'filePath', label: 'File Path', type: 'expression', defaultValue: '', required: true },
    ],
  },
  {
    id: 'take-screenshot',
    name: 'Take Screenshot',
    category: 'uiAutomation',
    group: 'Image',
    icon: '📸',
    description: 'Captures a screenshot of the screen or a specific element',
    color: '#1565C0',
    nodeType: 'activity',
    properties: [
      { name: 'savePath', label: 'Save Path', type: 'expression', defaultValue: '', required: true },
      { name: 'selector', label: 'Element Selector (optional)', type: 'string', defaultValue: '', description: 'Leave empty for full screen' },
    ],
  },
];
